name: Mover HU a In Progress

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  issues: write

jobs:
  move-hu-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Extraer número de HU desde la rama
        id: extract_hu
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          # Extrae el número de HU del nombre de la rama (ejemplo: hu-12-nombre)
          if [[ "$BRANCH_NAME" =~ hu-([0-9]+)- ]]; then
            echo "HU_NUMBER=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "No se encontró HU_NUMBER en la rama."
            exit 1
          fi

      - name: Mover la HU a la columna In Progress
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          IN_PROGRESS_COLUMN_ID: PVT_kwHOCfyr_s4BFLg_INPROGRESS
        run: |
          HU_NUMBER=${{ steps.extract_hu.outputs.HU_NUMBER }}
          ISSUE_ID=$(gh issue view $HU_NUMBER --json id | jq -r '.id')
          PROJECT_ID=$(gh project list --owner "@me" --format json | jq -r '.projects[] | select(.title == "Product Backlog") | .id')
          CARD_ID=$(gh api graphql -f query='query($project:ID!, $content:ID!) { projectV2ItemById(projectId: $project, id: $content) { id } }' -f project="$PROJECT_ID" -f content="$ISSUE_ID" | jq -r '.data.projectV2ItemById.id')
          gh api graphql -f query='mutation($card:ID!, $column:ID!) { moveProjectCard(input: {cardId: $card, columnId: $column}) { clientMutationId } }' -f card="$CARD_ID" -f column="$IN_PROGRESS_COLUMN_ID" || echo "No se pudo mover la HU a In Progress. Revisa el ID."
